site_name: Loterias Caixa
site_url: https://requisitos-de-software.github.io/2025.2-Grupo07/
repo_url: https://github.com/Requisitos-de-Software/2025.2-Grupo07
repo_name: GitHub

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
  logo: images/icon2.1.png
  favicon: images/icon2.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.mark

nav:
  - Início: index.md

  - Planejamento: 
    - Planejamento/Cronogramas.md
    - Planejamento/Tabela de contribuição.md
    - Planejamento/Heatmap.md
    - Planejamento/Ferramentas.md
    - Planejamento/Metodologia.md
  
  - Pré-Rastreabilidade:
    - Pré-rastreabilidade/AppsAnalisados.md
    - Pré-rastreabilidade/RichPicture.md    
  
  - Elicitação: 
    - Perfil de Usuário: Elicitação/Perfil de Usuário.md
    - Personas: Elicitação/Personas.md
    - Técnicas:
      - Análise de Documentos: Elicitação/Técnicas/Análise de Documentos.md
      - Entrevista: Elicitação/Técnicas/Entrevista.md
      - Observação: Elicitação/Técnicas/Observação.md
      - Glossário: Elicitação/Técnicas/Glossário.md
    - Priorização:
      - Three level scale: Elicitação/Priorização/Three level scale.md
      - Value, Cost and Risk: Elicitação/Priorização/Value, Cost and Risk.md
      - $100: Elicitação/Priorização/$100.md
      - MoSCoW: Elicitação/Priorização/MoSCoW.md


  - Modelagem: 
    - Modelagem/Casos de uso.md
    - Modelagem/Cenários.md
    - Modelagem/Especificação.md
    - Modelagem/História de usuário.md
    - Modelagem/Léxicos.md
    - Modelagem/NFR.md 
  
  - Verificação:   
    - Etapa 1:
      - Verificação/Inspeção Grupo 1 - Etapa 1.md
      - Verificação/Inspeção Grupo 7 - Etapa 1.md
    - Etapa 2:
      - Grupo + 1:
        - Verificação/Etapa 2/Grupo + 1/Listas de Verificações.md
        - Inspeção:
          - Verificação/Etapa 2/Grupo + 1/Inspeção/Perfil de Usuário.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/Personas.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/Análise de Documentos.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/Entrevista.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/Brainstorming.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/MoSCoW.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/$100.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/Spreadsheet.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/In or Out.md
      - Grupo 7:
        - Verificação/Etapa 2/Grupo 7/Listas de Verificações.md
        - Inspeção:
          - Verificação/Etapa 2/Grupo 7/Inspeção/Perfil de Usuário.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Personas.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Análise de Documentos.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Entrevista.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Observação.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Glossário.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Three level scale.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Value, Cost and Risk.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/$100.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/MoSCoW.md
        

  - Validação: Validação.md

  - Pós-Rastreabilidade: 
    - Pós-rastreabilidade/Forward from.md
    - Pós-rastreabilidade/Backward from.md
  
  - Apresentações: Apresentações.md
  
  - Atas:
    - Atas/Ata de reunião 1.md
    - Atas/Ata de reunião 2.md
    - Atas/Ata de reunião 3 (mudança de app).md
    - Atas/Ata de reunião 4.md
  
  - Termos de Uso: TermosDeUso.md

