site_name: Loterias Caixa
site_url: https://requisitos-de-software.github.io/2025.2-Grupo07/
repo_url: https://github.com/Requisitos-de-Software/2025.2-Grupo07
repo_name: GitHub

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
  logo: images/icon2.1.png
  favicon: images/icon2.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.mark

nav:
  - Início: index.md

  - Planejamento: 
    - Planejamento/Cronogramas.md
    - Planejamento/Tabela de contribuição.md
    - Planejamento/Heatmap.md
    - Planejamento/Ferramentas.md
    - Planejamento/Metodologia.md
    - Planejamento/Aplicativo Escolhido.md
  
  - Pré-Rastreabilidade:
    - Pré-rastreabilidade/AppsAnalisados.md
    - Pré-rastreabilidade/RichPicture.md    
  
  - Elicitação: 
    - Perfil de Usuário: Elicitação/Perfil de Usuário.md
    - Técnicas:
      - Análise de Documentos: Elicitação/Técnicas/Análise de Documentos.md
      - Entrevista: Elicitação/Técnicas/Entrevista.md
      - Observação: Elicitação/Técnicas/Observação.md
      - Glossário: Elicitação/Técnicas/Glossário.md
    - Priorização:
      - Three level scale: Elicitação/Priorização/Three level scale.md
      - Value, Cost and Risk: Elicitação/Priorização/Value, Cost and Risk.md
      - $100: Elicitação/Priorização/$100.md
      - MoSCoW: Elicitação/Priorização/MoSCoW.md

  - Validação: 
    - Prototipação: Validação/Prototipação.md
    - Validação informal: Validação/Validação informal.md

  - Modelagem: 
    - Modelagem/Casos de uso.md
    - Modelagem/Cenários.md
    - Modelagem/Especificação Suplementar.md
    - Modelagem/Léxicos.md
    - Ágil:
      - NFR: Modelagem/Ágil/NFR.md
      - Histórias de usuário: Modelagem/Ágil/História de usuário.md
      - Backlog: Modelagem/Ágil/Backlog.md
  
  
  
  - Verificação:   
    - Etapa 1:
      - Verificação/Inspeção Grupo 1 - Etapa 1.md
      - Verificação/Inspeção Grupo 7 - Etapa 1.md
    - Etapa 2:
      - Grupo + 1:
        - Verificação/Etapa 2/Grupo + 1/Listas de Verificações.md
        - Inspeção:
          - Verificação/Etapa 2/Grupo + 1/Inspeção/Perfil de Usuário.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/Personas.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/Análise de Documentos.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/Entrevista.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/Brainstorming.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/MoSCoW.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/$100.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/Spreadsheet.md
          - Verificação/Etapa 2/Grupo + 1/Inspeção/In or Out.md
      - Grupo 7:
        - Verificação/Etapa 2/Grupo 7/Listas de Verificações.md
        - Inspeção:
          - Verificação/Etapa 2/Grupo 7/Inspeção/Perfil de Usuário.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Personas.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Análise de Documentos.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Entrevista.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Observação.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Glossário.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Three level scale.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/Value, Cost and Risk.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/$100.md
          - Verificação/Etapa 2/Grupo 7/Inspeção/MoSCoW.md
    - Etapa 3:    
      - Grupo + 1:
        - Verificação/Etapa 3/Grupo + 1/Listas de Verificações.md
        - Inspeção:
          - Verificação/Etapa 3/Grupo + 1/Inspeção/Casos de Uso.md
          - Verificação/Etapa 3/Grupo + 1/Inspeção/Cenários.md
          - Verificação/Etapa 3/Grupo + 1/Inspeção/Especificação Suplementar.md
          - Verificação/Etapa 3/Grupo + 1/Inspeção/Léxicos.md
          - Verificação/Etapa 3/Grupo + 1/Inspeção/Geral.md
      - Grupo 7:
        - Verificação/Etapa 3/Grupo 7/Listas de Verificações.md
        - Inspeção:
          - Verificação/Etapa 3/Grupo 7/Inspeção/Casos de Uso.md
          - Verificação/Etapa 3/Grupo 7/Inspeção/Cenários.md
          - Verificação/Etapa 3/Grupo 7/Inspeção/Especificação Suplementar.md
          - Verificação/Etapa 3/Grupo 7/Inspeção/Léxicos.md
          - Verificação/Etapa 3/Grupo 7/Inspeção/Geral.md
    - Etapa 4:
      - Grupo + 1:
        - Verificação/Etapa 4/Grupo + 1/Listas de Verificações.md
        - Inspeção:
          - Verificação/Etapa 4/Grupo + 1/Inspeção/NFR.md
          - Verificação/Etapa 4/Grupo + 1/Inspeção/Histórias de Usuário.md
          - Verificação/Etapa 4/Grupo + 1/Inspeção/Backlog.md
          - Verificação/Etapa 4/Grupo + 1/Inspeção/Geral.md


      - Grupo 7:
        - Verificação/Etapa 4/Grupo 7/Listas de Verificações.md
        - Inspeção:
          - Verificação/Etapa 4/Grupo 7/Inspeção/NFR.md
          - Verificação/Etapa 4/Grupo 7/Inspeção/Histórias de Usuário.md
          - Verificação/Etapa 4/Grupo 7/Inspeção/Backlog.md
          - Verificação/Etapa 4/Grupo 7/Inspeção/Geral.md

  
    - Etapa 5:

      - Etapa 1:
          - Verificação/Etapa 5/Etapa 1/grupo_3.md
          - Verificação/Etapa 5/Etapa 1/grupo_7.md
          - Verificação/Etapa 5/Etapa 1/listas_de_verificações.md

      - Etapa 2:
          - Verificação/Etapa 5/Etapa 2/grupo_3.md
          - Verificação/Etapa 5/Etapa 2/grupo_7.md
          - Verificação/Etapa 5/Etapa 2/listas_de_verificações.md

      - Etapa 3:
          - Verificação/Etapa 5/Etapa 3/grupo_3.md
          - Verificação/Etapa 5/Etapa 3/grupo_7.md
          - Verificação/Etapa 5/Etapa 3/listas_de_verificações.md

      - Etapa 4:
          - Verificação/Etapa 5/Etapa 4/grupo_3.md
          - Verificação/Etapa 5/Etapa 4/grupo_7.md
          - Verificação/Etapa 5/Etapa 4/listas_de_verificações.md

      - Etapa 6:
          - Verificação/Etapa 5/Etapa 6/grupo_3.md
          - Verificação/Etapa 5/Etapa 6/grupo_7.md
          - Verificação/Etapa 5/Etapa 6/listas_de_verificações.md

    - Etapa 6:
      - Grupo + 1:
        - Verificação/Etapa 6/Grupo + 1/Listas de Verificações.md     
        - Verificação/Etapa 6/Grupo + 1/Inspeção.md  
      - Grupo 7:
        - Verificação/Etapa 6/Grupo 7/Listas de Verificações.md
        - Verificação/Etapa 6/Grupo 7/Inspeção.md

  - Pós-Rastreabilidade: 
    - Pós-rastreabilidade/Forward from.md
    - Pós-rastreabilidade/Backward from.md
    - Pós-rastreabilidade/matriz_geral.md
    - Pós-rastreabilidade/modelo_toranzo.md
  
  - Entrega final:
    - App selecionado: Entrega final/app selecionado.md
    - Apresentações: Entrega final/apresentacoes.md
    - Artefatos criados: Entrega final/artefatos criados.md
    - Considerações finais: Entrega final/Consideracoes finais.md
    - Ferramentas utilizadas: Entrega final/ferramentas utilizadas.md
    - Planejamento: Entrega final/planejamento.md
    - Resultados alcançados: Entrega final/Resultados alcancados.md
    - Técnicas utilizadas: Entrega final/tecnicas utilizadas.md
    - Validação: Entrega final/validacao.md
    - Verificação: Entrega final/verificacao.md
    - tabela de contrivuição final: Entrega final/tabela de contribuição final.md

  
  - Apresentações: Apresentações.md
  
  - Atas:
    - Atas/Ata de reunião 1.md
    - Atas/Ata de reunião 2.md
    - Atas/Ata de reunião 3 (mudança de app).md
    - Atas/Ata de reunião 4.md
  
  - Termos de Uso: TermosDeUso.md

